version: "3"
services:
  web:
    container_name: web
    build: .
    ports:
      - 8443:8443
    volumes:
      - ./src:/go/src
    tty: true
    depends_on:
      - db
  db:
    container_name: db
    image: mysql:5.6
    platform: linux/amd64 #linux/amd64にエミュレート
    volumes:
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
      - ./tmp/db:/var/lib/mysql
      - ./initdb:/docker-entrypoint-initdb.d
    environment:
      MYSQL_DATABASE: gwp
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      # MYSQL_USER: user
      # MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
