version: "3"
services:
  web:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./src:/go/src
    tty: true
    depends_on:
      - db
  db:
    image: postgres:14.3-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata